version: '3'

services:
  build:
    build:
      context: .
      target: build
    volumes:
      - .:/app

  serve:
    build:
      context: .
      target: serve
      dockerfile: Dockerfile
    ports:
      - 80:80
