version: '3.8'

services:
  build:
    build:
      context: .
      target: build
    volumes:
      - .:/app

  serve:
    build:
      context: .
      target: serve
      dockerfile: Dockerfile
    ports:
      - 80:80

  app:
    build: .
    volumes:
      - .:/app
    command: npm run build

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 8080:80
    depends_on:
      - app
